### ISSUE TITLE
Netlify : undefined set-cookie

### ISSUE THREAD

**Issue by klevron** [unjs/nitro#1938]
### Environment

Node : 18.17.0
Nuxt 3.7.4 / Nitro 2.6.3
Nuxt 3.8.1 / Nitro 2.8.0

### Reproduction

Sorry I can't provide netlify link for the moment, I will try to setup one later if it's really needed (please take a look at description).

### Describe the bug

An undefined `Set-Cookie` header is sent on netlify :

![image](https://github.com/unjs/nitro/assets/4560725/fbb898f5-3676-42bc-87aa-08b724226f8f)

### Additional context

We have another site with Nuxt 3.6.5 / Nitro 2.5.2 and it works fine.

**Comment by paro-paro** [comment]
I am having the exact same issue. Netlify server is setting a weird undefined cookie on every get request.  I am on latest nuxt 3.9.0 (nitro 2.8.1)

https://amazing-alfajores-2826d3.netlify.app/invest

<img width="553" alt="Screenshot 2024-01-10 at 20 12 05" src="https://github.com/unjs/nitro/assets/43136874/3c01e3d0-3ac8-4b09-8b27-fab93fcf5e40">

**Comment by pi0** [comment]
A reproduction repository would be very helpful to investigate and possibly fix any issues 🙏🏼

**Comment by djm-innonova** [comment]
We are experiencing this problem as well on 3.9.0 (nitro 2.8.1) - however we noticed it was already introduced when we upgraded earlier from 3.6.3 to 3.8.2 of Nuxt.

Interestingly I tried to downgrade to Nuxt 3.6.5 as originally mentioned in this post, however because of the way the dependencies are specified I anyway ended up with 2.8.1 of nitro. I then tried locking down the version of nitro to 2.5.2 (as originally specified in Nuxt 3.6.5 package.json) and still saw the `Set-Cookie: undefined` issue when deployed in Netlify.

After using the lock file we had from our previous 3.6.3 version we got it fixed now, but this indicates that the problem is not in nitro, but rather in some other dependency - I am suspecting `h3`, but did not have time to investigate if that is really the case.

**Comment by klevron** [comment]
> Interestingly I tried to downgrade to Nuxt 3.6.5 as originally mentioned in this post

It works with :

```
  "nitropack": "2.5.2",
  "nuxt": "3.6.5",
```

**Comment by djm-innonova** [comment]
@klevron that's what I tried, still didn't work for me (unless I messed something else up) - would be interesting to know if that still works for you if you delete and recreate your lock file?

**Comment by remihuigen** [comment]
Still having this issue with Nuxt 3.12.2 and Nitro 2.9.6.... Any updates?

**Comment by hlassiege** [comment]
For the record, I had the same problem on nuxt 3.16 on netlify.

I noticed that I used the netlify_legacy preset.

I fixed that by using a compatibility date : 

    compatibilityDate: "2024-05-07",

then it started with the netlify preset. And now it works, I don't have this weird cookie anymore.
